import { Title } from '@scientist-softserv/webstore-component-library'

const TermsOfUse = () => (
  <div className='container'>
    <Title title='Website Terms of Use' style={{ marginTop: '1rem'}} />
    {termsOfUse}
  </div>
)

export default TermsOfUse

/* eslint-disable max-len, react/no-unescaped-entities */
const termsOfUse =(
  <div>
    <style type="text/css" dangerouslySetInnerHTML={{__html: "\n    .awlist1 {\n        list-style: none;\n        counter-reset: awlistcounter5_0\n    }\n\n    .awlist1>li:before {\n        content: counter(awlistcounter5_0) ')';\n        counter-increment: awlistcounter5_0\n    }\n" }} />
    <div>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><strong><span style={{color: '#3d3d3d'}}>Last Updated: October 19, 2023</span></strong></p>
      <p style={{marginTop: '14pt', marginBottom: '14pt', textAlign: 'left', fontSize: '10.5pt', backgroundColor: '#f8f8f8'}}><span>Welcome to PhenoVista’s website powered by Scientist.com (the "</span><strong><span>Website</span></strong><span>").</span></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>BEFORE USING THE SERVICES (DEFINED BELOW), PLEASE READ THE FOLLOWING WEBSITE TERMS OF USE (“</span><strong><span style={{color: '#3d3d3d'}}>TofU</span></strong><span style={{color: '#3d3d3d'}}>”) TERMS CAREFULLY.</span><span>&nbsp;</span></p>
      <p style={{marginTop: '14pt', marginBottom: '14pt', fontSize: '10.5pt', backgroundColor: '#f8f8f8'}}><span>Please note that in these TofU,&nbsp;</span><span style={{color: '#3d3d3d'}}>"</span><strong><span style={{color: '#3d3d3d'}}>Services</span></strong><span style={{color: '#3d3d3d'}}>" means the Website and its associated software, hardware, infrastructure, application programming interface(s) ("</span><strong><span style={{color: '#3d3d3d'}}>API</span></strong><span style={{color: '#3d3d3d'}}>"), content, trademarks and other associated materials.&nbsp;</span><span>Refences to “Services” therefore does not mean the goods or services offered for sale or sold to the Client by PhenoVista Biosciences, Inc. (“</span><strong><span>Phenovista</span></strong><span>”) via the Website.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span>By registering for and/or accessing or using the Services, the&nbsp;</span><span style={{color: '#3d3d3d'}}>individuals accessing or using the Services are agreeing:</span></p>
      <ol type={1} className="awlist1" style={{margin: '0pt', paddingLeft: '0pt'}}>
        <li style={{marginLeft: '36pt', textIndent: '-18pt', fontSize: '10.5pt', color: '#3d3d3d'}}><span style={{width: '13pt', font: '7pt "Times New Roman"', display: 'inline-block'}}>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>that they have read, understood and accept these TofU (and the Scientist.com.com Policies (defined below) and PhenoVista’s privacy policy); and</li>
        <li style={{marginLeft: '36pt', marginBottom: '12pt', textIndent: '-18pt', fontSize: '10.5pt', color: '#3d3d3d'}}><span style={{width: '11.95pt', font: '7pt "Times New Roman"', display: 'inline-block'}}>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>they are either the Client in their own right, or where they represent an organization in their access and use of the Services, that they are binding that Client to them and any future modifications thereto and have the authority to do so.</li>
      </ol>
      <p style={{marginTop: '14pt', marginBottom: '14pt', fontSize: '10.5pt', backgroundColor: '#f8f8f8'}}><span>IF AT ANY TIME YOU DO NOT AGREE TO THESE TOFU, PLEASE IMMEDIATELY TERMINATE YOUR USE OF THE SERVICES. IF YOU ARE UNHAPPY WITH ANY ASPECT, OR DO NOT HAVE THE AUTHORITY TO BIND THE CLIENT TO THESE TOFU, YOU SHOULD NOT ACCESS THE WEBSITE OR THE SERVICES FOR THAT CLIENT.&nbsp;</span></p>
      <p style={{marginTop: '14pt', marginBottom: '14pt', fontSize: '10.5pt'}}><span style={{color: '#141414'}}>The “</span><strong><span style={{color: '#141414'}}>Client</span></strong><span style={{color: '#141414'}}>” is either the individual accessing or using the Website on its own behalf, or the legal entity whose representative is accessing or using the Website on its behalf. “</span><strong><span style={{color: '#141414'}}>Users</span></strong><span style={{color: '#141414'}}>” are individuals representing an organization in their access or use of the Services (including the Website).</span></p>
      <p style={{marginTop: '0pt', marginBottom: '14pt', fontSize: '10.5pt'}}><span style={{color: '#141414'}}>References in these TofU to “</span><strong><span style={{color: '#141414'}}>you</span></strong><span style={{color: '#141414'}}>” means the Client, unless specified or the context requires otherwise. “</span><strong><span style={{color: '#141414'}}>Your</span></strong><span style={{color: '#141414'}}>” shall be construed accordingly.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>These TofU apply to all uses of the Services. These TofU are a legal contract between the Client and&nbsp;</span><span style={{color: '#141414'}}>The Assay Depot, Inc., (d.b.a. Scientist.com), 505 Lomas Santa Fe Drive, Suite 110, Solana Beach, San Diego, CA 90275 (“</span><strong><span style={{color: '#141414'}}>Scientist.com</span></strong><span style={{color: '#141414'}}>”)</span><span style={{color: '#3d3d3d'}}>&nbsp;regarding use of the Services by the Client and/or its Users. PhenoVista is also a party to these TofU for the sections indicated herein.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>Together, the Client and Scientist.com are each referred to herein individually as a "</span><strong><span style={{color: '#3d3d3d'}}>Party</span></strong><span style={{color: '#3d3d3d'}}>" or collectively as the "</span><strong><span style={{color: '#3d3d3d'}}>Parties</span></strong><span style={{color: '#3d3d3d'}}>". Reference to Parties also includes Phenovista where required in the context of Phenovista being a party to these TofU for the sections indicated.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>Client shall procure that its Users comply with the these TofU and shall be liable to Scientist.com for any act or omission of its Users and/or any breach of these TofU by any of its Users as if such breach was its own.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>Any order resulting from a request to Phenovista made via the Website must be placed via the Website.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>When using the Services, the Client and Users will be subject to any additional posted guidelines, policies or rules of Scientist.com applicable to specific Services and features, existing or future, which may be posted from time to time (collectively, the "</span><strong><span style={{color: '#3d3d3d'}}>Scientist.com</span></strong><span style={{color: '#3d3d3d'}}>&nbsp;</span><strong><span style={{color: '#3d3d3d'}}>Policies</span></strong><span style={{color: '#3d3d3d'}}>"). The Scientist.com Policies are hereby incorporated by reference into these TofU. Scientist.com may modify or update the Scientist.com Policies from time to time so please check the top of the page of each of the Scientist.com Policies to see when they were last updated. If there is any contradiction between the Scientist.com Policies and the then current version of these TofU, then the relevant Scientist.com Policy shall take precedence in relation to the subject matter thereof.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '13.8pt', fontSize: '10.5pt'}}><strong><span>Eligibility</span></strong></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>In order to use the Services, the Client and each User (as applicable) must either be the age of majority in your jurisdiction, an emancipated minor, or possess legal parental or guardian consent, and fully able and competent to enter into the terms, conditions, obligations, affirmations, representations and warranties set forth in these TofU and be duly authorized to bind the Client to the same. The Client represents that each User meets the eligibility requirements in this Section. In any case, the Client affirms that its Users are over the age of 13, as the Services are not intended for children under 13.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>The Client represents that neither it nor any of its Users will use the Services in violation of any applicable laws and regulations or rights of third parties, including without limitation the Export Administration Regulations, the International Traffic in Arms Regulations, and country-specific economic sanctions programs implemented by the Office of Foreign Assets Control, intellectual property rights and/or rights of confidentiality.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '13.8pt', fontSize: '10.5pt'}}><strong><span style={{color: '#3d3d3d'}}>Privacy&nbsp;</span></strong></p>
      <p style={{marginTop: '0pt', marginBottom: '0pt', fontSize: '10.5pt'}}><span>Phenovista and you may decide to share Personal Data</span><span>&nbsp;&nbsp;</span><span>excluding Special Category Personal Data relating to themselves, their employees and other third parties via the Website (“</span><strong><span>Personal</span></strong><span>&nbsp;</span><strong><span>Data</span></strong><span>”).</span><span>&nbsp;&nbsp;</span><span>As these are business to business transactions, it is expected that Personal Data to be shared will be basic e.g. business contact names and email addresses.</span><span>&nbsp;&nbsp;</span></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span>You warrant, represent and undertake that you will not and will not allow any third party to place Special Category Personal Data on the Website or within any attachments submitted on the Website. You instruct Phenovista (who in turn may instruct Scientist.com) to remove any such Special Category Personal Data placed on or sent via the Website that it becomes aware of, although neither Phenovista nor Scientist.com have any obligation to check for this or to do so.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span>“</span><strong><span>Special Category Personal Data</span></strong><span>” means information which reveals racial or ethnic origin, political opinions, religious or philosophical beliefs, or trade union membership, genetic data, biometric data and data concerning health or a persons sex life or sexual orientation and any data relating to criminal convictions and offences.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span>You and Phenovista shall each be deemed a Controller of the Personal Data placed on, shared and received by each of you and Phenovista via the Website.</span><span>&nbsp;&nbsp;</span><span>“</span><strong><span>Controller</span></strong><span>” means the natural or legal person, public authority, agency or other body which alone, or jointly with others, determines the purposes and means of the Processing of personal data.</span></p>
      <p style={{marginTop: '0pt', marginLeft: '19.5pt', marginBottom: '0pt', fontSize: '10.5pt'}}><span>&nbsp;</span></p>
      <p style={{marginTop: '0pt', marginLeft: '19.5pt', marginBottom: '0pt', fontSize: '10.5pt'}}><span>“</span><strong><span>Process</span></strong><span>” means any operation or set of operations which is performed on Personal Data or on sets of Personal Data, whether or not by automated means, such as the collection, recording, organisation, structuring, storage, adaptation or alteration, retrieval, consultation, use, disclosure by transmission, and</span><span>&nbsp;&nbsp;</span><span>dissemination or otherwise making available, alignment or combination, restriction, erasure or destruction and "</span><strong><span>Processed</span></strong><span>" and "</span><strong><span>Processing</span></strong><span>" shall be construed accordingly.</span></p>
      <p style={{marginTop: '0pt', marginLeft: '19.5pt', marginBottom: '0pt', fontSize: '10.5pt'}}><span>&nbsp;</span></p>
      <p style={{marginTop: '0pt', marginLeft: '19.5pt', marginBottom: '0pt', fontSize: '10.5pt'}}><span>In respect of any Personal Data which Client and Phenovista share and or Process</span><span>&nbsp;&nbsp;</span><span>between them via the Website (including where Scientist.com provides Personal Data to Phenovista and Client acting as Processor appointed by Phenovista) Scientist.com shall have no liability in respect to such data sharing/processing arrangement between</span><span>&nbsp;&nbsp;</span><span>Phenovista and Client.</span><span>&nbsp;&nbsp;</span></p>
      <p style={{marginTop: '0pt', marginLeft: '19.5pt', marginBottom: '0pt', fontSize: '10.5pt'}}><span>&nbsp;</span></p>
      <p style={{marginTop: '0pt', marginLeft: '19.5pt', marginBottom: '0pt', fontSize: '10.5pt'}}><span>“</span><strong><span>Processor</span></strong><span>” means a natural or legal person, public authority, agency or other body which Processes Personal Data on behalf of the Controller.</span></p>
      <p style={{marginTop: '0pt', marginLeft: '19.5pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span>&nbsp;</span></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span>In accordance with Phenovista’s privacy policy on the Website from time to time, Phenovista may share all Personal Data placed on the Website with Scientist.com as its Processor and also authorize Scientist.com to be a separate Controller thereof for the purposes of using such Personal Data in accordance with Scientist.com’s own privacy policy, available from time to time here:&nbsp;</span><a href="https://phenovista.vercel.app/privacy-policy/scientist-privacy-policy" style={{textDecoration: 'none'}}><span style={{color: '#0072bc'}}>https://phenovista.vercel.app/privacy-policy/scientist-privacy-policy</span></a><span>.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span>Phenovista and Scientist.com may modify or update their policies from time to time so please make sure you check the Website for the most current version that applies from time to time.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '0pt', fontSize: '10.5pt'}}><span>You will only transfer Personal Data to Phenovista via the Website (whether such transfer is made by Users representing the Client on the Website or otherwise) where</span><u><span>&nbsp;</span></u><span>you have obtained the valid consent of the individual to whom the Personal Data relates (“</span><strong><span>Data Subject</span></strong><span>”) to the transfer to Phenovista under applicable data protection laws.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span>You agree that (a) in providing and continuing to provide Personal Data to Phenovista via the Website and (b) by selecting to use the Website and engage with Phenovista in a Restricted Country, you shall have obtained the consent of the applicable Data Subjects whose Personal Data is shared with Phenovista via the Website and your provision of such Personal Data will be consenting to the disclosure of such Personal Data to a Restricted Country. You shall provide such information to evidence such consents to Scientist.com and/or Phenovista as they may request from time to time. “</span><strong><span>Restricted Country</span></strong><span>” means a country, territory or jurisdiction (i) which is not covered by an adequacy determination by a competent authority with jurisdiction over the data exporter or (ii) otherwise in relation to which a transfer restriction applies under the applicable laws of the data exporter.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '13.8pt', fontSize: '10.5pt'}}><strong><span style={{color: '#3d3d3d'}}>Terms of Purchase</span></strong></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>The separate “</span><strong><span style={{color: '#3d3d3d'}}>Terms and Conditions for Purchases</span></strong><span style={{color: '#3d3d3d'}}>” from time to time are available on the Website and apply to Orders (as defined therein) placed via the Website and set out how such Orders are entered into and become binding. You should carefully review them before placing a request or an order for goods or services from PhenoVista via the Website.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '13.8pt', fontSize: '10.5pt'}}><strong><span style={{color: '#3d3d3d'}}>Modification of these TofU</span></strong></p>
      <p style={{marginTop: '14pt', marginBottom: '14pt', fontSize: '10.5pt', backgroundColor: '#f8f8f8'}}><span style={{color: '#3d3d3d'}}>Scientist.com reserves the right, at our discretion, to change, modify, add, or remove portions of these TofU at any time for any reason, and we may notify you of such changes by a change to the "Last Updated" date set forth above and/or other reasonable means to be determined at our discretion. All changes shall be effective immediately.&nbsp;</span><span>Every time the Client or any User accesses or uses the Services, the TofU in force at the time of such access shall apply.</span><span>&nbsp;&nbsp;</span><span>Please check the top of this page to see when these TofU were last updated.&nbsp;</span></p>
      <p style={{marginTop: '0pt', marginBottom: '13.8pt', fontSize: '10.5pt'}}><strong><span style={{color: '#3d3d3d'}}>Ownership; Proprietary Rights</span></strong></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>As between the Parties, the Services including the API, content, visual interfaces, interactive features, information, graphics, design, compilation, computer code, software, services, and all other elements of the Services that are provided by Scientist.com ("</span><strong><span style={{color: '#3d3d3d'}}>Scientist.com Materials</span></strong><span style={{color: '#3d3d3d'}}>") are owned and/or licensed for use by Scientist.com. Scientist.com Materials owned by Scientist.com include without limitation, trademarks, service marks, trade dress, or are copyrighted works of Scientist.com in the U.S. and/or other countries. The compilation of all content on the Services is the exclusive property of Scientist.com and is protected by U.S. and international copyright laws. Scientist.com Materials do not include Contributed Content (as defined below).</span></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>Except as expressly authorized by Scientist.com, you agree not to sell, license, distribute, copy, modify, publicly perform or display, transmit, publish, edit, adapt, create derivative works from, or otherwise make unauthorized use of the Services or the Scientist.com Materials. Scientist.com reserves all rights not expressly granted in these TofU. You shall not acquire any right, title, or interest to the Scientist.com Materials, except for the limited rights set forth in these Terms. Some Scientist.com Materials are licensed under a separate license, such as the GNU Lesser General Public License, version 2.1, or other open source license. In the event of a conflict between these TofU and any separate license, the separate license will prevail with respect to the applicable Scientist.com Materials.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '13.8pt', fontSize: '10.5pt'}}><strong><span style={{color: '#3d3d3d'}}>Content on the Services</span></strong></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>PhenoVista may offer for sale and or sell goods and services on the Website. Content submitted, posted, uploaded, or otherwise added to the Services by third parties including PhenoVista will be herein known as "</span><strong><span style={{color: '#3d3d3d'}}>Third Party Content</span></strong><span style={{color: '#3d3d3d'}}>". We are not responsible for examining or evaluating, and we do not warrant the offerings of, any of these businesses or individuals or any Third Party Content. Scientist.com does not assume any responsibility or liability for the actions, services or products of any third party and/or Third Party Content. You should carefully review PhenoVista’s privacy policies and Terms and Conditions for Purchases. The following applies to content encountered in use of the Services:</span></p>
      <table cellSpacing={0} cellPadding={0} style={{borderCollapse: 'collapse'}}>
        <tbody>
          <tr>
            <td style={{padding: '6pt', verticalAlign: 'top'}}>
              <p style={{marginTop: '0pt', marginBottom: '0pt', textAlign: 'justify', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>a. All trademarks, service marks, or trade dress not owned by Scientist.com that are encountered in</span></p>
              <p style={{marginTop: '0pt', marginBottom: '0pt', textAlign: 'justify', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>your use of the Services are the property of their respective owners, who may or may not be affiliated&nbsp;</span></p>
              <p style={{marginTop: '0pt', marginBottom: '0pt', textAlign: 'justify', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>with, connected to, or sponsored by Scientist.com.</span></p>
            </td>
          </tr>
          <tr>
            <td style={{padding: '6pt', verticalAlign: 'top'}}>
              <p style={{marginTop: '0pt', marginBottom: '0pt', textAlign: 'justify', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>b. Third Party Content comprises a large portion of the content on the Services, and Scientist.com does not&nbsp;</span></p>
              <p style={{marginTop: '0pt', marginBottom: '0pt', textAlign: 'justify', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>warrant that descriptions, pricing, service turn around times, or other content on the Services is accurate,&nbsp;</span></p>
              <p style={{marginTop: '0pt', marginBottom: '0pt', textAlign: 'justify', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>complete, reliable, current, or error-free.</span></p>
            </td>
          </tr>
          <tr>
            <td style={{padding: '6pt', verticalAlign: 'top'}}>
              <p style={{marginTop: '0pt', marginBottom: '0pt', textAlign: 'justify', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>c. Except where specifically noted otherwise, prices encountered on the Services represent the full retail&nbsp;</span></p>
              <p style={{marginTop: '0pt', marginBottom: '0pt', textAlign: 'justify', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>price of the service or product itself, as determined by a third party. Prices may or may not include</span></p>
              <p style={{marginTop: '0pt', marginBottom: '0pt', textAlign: 'justify', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>taxes and/or the cost of shipping samples or products to or from third parties. It is solely your</span></p>
              <p style={{marginTop: '0pt', marginBottom: '0pt', textAlign: 'justify', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>responsibility to understand all costs and fees associated with a product or service prior to placing</span></p>
              <p style={{marginTop: '0pt', marginBottom: '0pt', textAlign: 'justify', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>an Order and entering into a binding contract to use or acquire that product or service.&nbsp;</span></p>
              <p style={{marginTop: '0pt', marginBottom: '0pt', textAlign: 'justify', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>Scientist.com does not assume any financial or legal responsibility or liability as a result of your use</span></p>
              <p style={{marginTop: '0pt', marginBottom: '0pt', textAlign: 'justify', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>&nbsp;</span><span style={{color: '#3d3d3d'}}>of the Services.</span></p>
              <p style={{marginTop: '0pt', marginBottom: '0pt', textAlign: 'justify', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>&nbsp;</span></p>
            </td>
          </tr>
        </tbody>
      </table>
      <p style={{marginTop: '0pt', marginBottom: '13.8pt', fontSize: '10.5pt'}}><strong><span style={{color: '#3d3d3d'}}>Contributed Content</span></strong></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>Some features of the Services allow you and your Users to submit content (“</span><strong><span style={{color: '#3d3d3d'}}>User Content</span></strong><span style={{color: '#3d3d3d'}}>”). You retain ownership of any intellectual property rights that you hold in that content. In short, what belongs to you stays yours.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>Users may post User Content, including, without limitation, reviews and other content; send notices and other communications; and submit suggestions, ideas, comments, questions, or other information, so long as such content is not illegal, obscene, threatening, defamatory, invasive of privacy, infringing of intellectual property rights, rights of confidentiality or other rights, or otherwise injurious to third parties or objectionable and does not consist of or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings, or any form of "spam." Neither the Client nor any Users may use a false e-mail address, impersonate any person or entity, or otherwise mislead as to the origin of a card or other content. Scientist.com has the right but not the obligation to monitor and edit or remove any activity or content. Scientist.com takes no responsibility and assumes no liability for any content posted by you or any third party (including without limitation by or on behalf of PhenoVista).</span></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>You expressly authorize Scientist.com to provide: (i) User Content placed by you on the Website and information provided by you in Orders, requests via the Webstore and Purchase Orders to Phenovista. Phenovista expressly authorizes Scientist.com to provide content placed on the Website by Phenovista responding to your Website requests, including Quotes, Orders, invoices and all correspondence related thereto to you. Scientist.com is not responsible for the use of any such information by Phenovista or you and the provision of such information to you or Phenovista (as applicable) is not a breach by Scientist.com of any terms of these TofU or the Terms and Conditions of Purchases (including without limitation, obligations of confidentiality). This section takes precedence over any conflicting term in these TofU or Terms and Conditions of Purchases.</span><span style={{color: '#3d3d3d'}}>&nbsp;&nbsp;</span><span style={{color: '#3d3d3d'}}>Phenovista is a party to these TofU for the purposes of this paragraph.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>PhenoVista and you hereby agree with each other to keep all use User Content and content provided by PhenoVista confidential and not to disclose same to third parties without your or PhenoVista’s consent, as the case may be.</span><span style={{color: '#3d3d3d'}}>&nbsp;&nbsp;</span><span style={{color: '#3d3d3d'}}>For clarity, User Content and content provided by PhenoVista to you shall not be considered “confidential” if it: (a) was known to the recipient prior to receipt without an obligation of confidentiality; (b) at the time of disclosure to recipient was generally available to the public, or which after disclosure hereunder, becomes generally available to the public through no fault of the recipient; (c) is hereafter made available to the recipient from any third party having a right to do so on a non-confidential basis; or (d) was independently developed by the recipient without use of the Confidential Information. In the event you enter into an Order, the confidentiality provisions set forth in the governing Terms and Conditions of Purchases supersede this paragraph.</span><span style={{color: '#3d3d3d'}}>&nbsp;&nbsp;</span><span style={{color: '#3d3d3d'}}>Phenovista is a party to these TofU solely for the purposes of this paragraph.</span></p>
      <p style={{marginTop: '0pt', marginLeft: '42.5pt', marginBottom: '12pt', textIndent: '-42.5pt', fontSize: '10.5pt'}}><span style={{backgroundColor: '#ffffff'}}>You acknowledge and agree that Scientist.com shall have access to and visibility of all traffic and content on the Website. To the extent such traffic or content includes any Customer information or data relating to Orders and/or requests for Orders (“</span><strong><span style={{backgroundColor: '#ffffff'}}>Order Data</span></strong><span style={{backgroundColor: '#ffffff'}}>”), Scientist.com</span><span style={{color: '#222222'}}>&nbsp;</span><span style={{color: '#222222'}}>does not claim ownership of this, but does require a license to use such Order Data. Accordingly, you hereby grant Scientist.com a non-exclusive, transferable, sub-licensable, royalty-free, worldwide right and license to do the following with the Order Data: host, use, display on the Website, translate,</span><span style={{backgroundColor: '#ffffff'}}>&nbsp;</span><span style={{backgroundColor: '#ffffff'}}>train ML models, run reports and/or</span><span style={{color: '#222222'}}>&nbsp;</span><span style={{color: '#222222'}}>create derivative works or meta data from it (i.e. who orders what, where and when etc.) (“</span><strong><span style={{color: '#222222'}}>Meta Data</span></strong><span style={{color: '#222222'}}>”). Scientist.com may also use the Order Data as necessary to operate and provide the Website and Services and to perform its obligations and exercise its rights under these Tof U, Orders and/or the Website Terms and Conditions of Purchase.&nbsp;</span><span style={{color: '#3d3d3d'}}>This license continues even if you stop using the Services.</span><span style={{color: '#222222'}}>&nbsp;</span><span style={{color: '#222222'}}>Scientist.com</span><span style={{color: '#222222'}}>&nbsp;</span><span style={{backgroundColor: '#ffffff'}}>owns all right and title to any and all Meta Data, but to the extent Scientist.com publishes any Meta Data, it will only do so to the extent that no Customer or PhenoVista identifying information is disclosed.&nbsp;</span></p>
      <p style={{marginTop: '0pt', marginBottom: '13.8pt', fontSize: '10.5pt'}}><strong><span style={{color: '#3d3d3d'}}>Confidentiality Obligations between Scientist.com and Client</span></strong></p>
      <p style={{marginTop: '0pt', marginBottom: '13.8pt', fontSize: '10.5pt'}}><span>This Section applies between Scientist.com and Client and not PhenoVista.</span><span>&nbsp;&nbsp;</span><span>This Section and references to “Party”, “Parties”, “Recipient” and “Disclosing Party” contained in this Section shall be construed accordingly as being references to Client and/or Scientist.com (as applicable).</span></p>
      <p style={{marginTop: '0pt', marginBottom: '0pt', textIndent: '72pt', widows: 0, orphans: 0, fontSize: '10.5pt'}}><span>(a)</span><span style={{width: '27.05pt', textIndent: '0pt', display: 'inline-block'}}>&nbsp;</span><u><span>Confidential Information</span></u><span>. “</span><u><span>Confidential Information</span></u><span>” means any and all confidential, proprietary and/or trade secret information or materials that are disclosed by or on behalf of a Party or its affiliates (the “</span><u><span>Disclosing Party</span></u><span>”) to the other Party or its affiliates (the “</span><u><span>Recipient</span></u><span>”) under these T&amp;Cs or as a result of the Client using the Services, whether in written, oral or other form. Confidential Information includes, without limitation, content placed on the Website by either Party, Client requests made via the Website and Disclosing Party information contained in any associated purchase order, Order or invoice, business plans, business practices, business records, compounds, concepts, current and past distribution and production arrangements, customer information, data, designs, devices, employee information, financial information, formulas, intellectual property, inventions, know-how, marketing and sales strategies, materials, methods, plans, procedures, processes,&nbsp;</span><span style={{letterSpacing: '-0.15pt'}}>products and future products,</span><span>&nbsp;</span><span style={{letterSpacing: '-0.15pt'}}>protocols</span><span>,&nbsp;</span><span style={{letterSpacing: '-0.15pt'}}>research and development data and plans</span><span>, records, software, specifications, technical information and trade secrets.&nbsp;</span></p>
      <p style={{marginTop: '0pt', marginBottom: '0pt', widows: 0, orphans: 0, fontSize: '10.5pt'}}><span>&nbsp;</span></p>
      <p style={{marginTop: '0pt', marginBottom: '0pt', textIndent: '72pt', widows: 0, orphans: 0, fontSize: '10.5pt'}}><span>(b)</span><span style={{width: '26.61pt', textIndent: '0pt', display: 'inline-block'}}>&nbsp;</span><u><span>Non-Disclosure and Non-Use</span></u><span>. Subject to paragraphs (c) and (d) of this Section, Recipient shall maintain the Confidential Information in confidence, and not disclose the Confidential Information to any third party, or use the Confidential Information for its benefit or the benefit of any third party, without the prior written consent of the Disclosing Party. Recipient shall use the Confidential Information only as is necessary to fulfill its obligations pursuant to these T&amp;Cs and any Order (and in the case of Scientist.com, to perform the Services), and shall limit any disclosure to its affiliates and its/their directors, officers, employees, contractors, agents and permitted subcontractors (“</span><u><span>Representatives</span></u><span>”) on a “need-to-know” basis for such purposes. Recipient shall cause its Representatives to comply with the confidentiality obligations set forth in this&nbsp;</span><u><span>Section&nbsp;</span></u><span>and shall be liable for any violation of the confidentiality obligations set forth in this&nbsp;</span><u><span>Section&nbsp;</span></u><span>by any of its Representatives. Recipient shall protect the Disclosing Party’s Confidential Information with at least the same degree of care that Recipient uses to protect its own Confidential Information, but in no case less than reasonable care. Phenovista is not a Representative of Scientist.com.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '0pt', widows: 0, orphans: 0, fontSize: '10.5pt'}}><span>&nbsp;</span></p>
      <p style={{marginTop: '0pt', marginBottom: '0pt', textIndent: '72pt', widows: 0, orphans: 0, fontSize: '10.5pt'}}><span>(c)</span><span style={{width: '27.59pt', textIndent: '0pt', display: 'inline-block'}}>&nbsp;</span><u><span>Exceptions</span></u><span>. Confidential Information shall not include any information that Recipient can demonstrate as evidenced by competent written evidence: (i) previously was in its possession, as shown by its pre-existing records, without violation of any obligation of confidentiality; (ii) has become publicly known through no wrongful act of Recipient; (iii) was received by Recipient without breach of these T&amp;Cs from a third party without restriction as to the use and disclosure of the information; or (iv) was independently developed by Recipient without use of the Confidential Information.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '0pt', textIndent: '72pt', widows: 0, orphans: 0, fontSize: '10.5pt'}}><span>&nbsp;</span></p>
      <p style={{marginTop: '0pt', marginBottom: '0pt', textIndent: '72pt', widows: 0, orphans: 0, fontSize: '10.5pt'}}><span>(d)</span><span style={{width: '26.36pt', textIndent: '0pt', display: 'inline-block'}}>&nbsp;</span><u><span>Authorized Disclosures</span></u><span>. Confidential Information may be disclosed by Recipient as authorized in these TofU. Scientist.com may disclose Confidential Information to Phenovista for the purposes of complying with its obligations under any Order and the Terms and Conditions of Purchases. Confidential Information may also be disclosed by Recipient if Recipient is required by a valid order of a court or other governmental body or otherwise required by the law to disclose such Confidential Information;&nbsp;</span><em><span>provided</span></em><span>,&nbsp;</span><em><span>however</span></em><span>, that Recipient shall, to the extent allowable under applicable law and/or regulation, give the Disclosing Party timely written notice of such a requirement before doing so and shall, at the cost of the Disclosing Party, cooperate with the Disclosing Party to seek a protective order, confidential treatment or other appropriate measures. Scientist.com shall also have the rights to use and disclose the Confidential Information as set forth in the Website Terms of Use (“</span><u><span>Terms or Use</span></u><span>”) and in the event of any conflict between such Terms of Use and any provision in these T&amp;C’s, the Terms of Use shall prevail.</span></p>
      <p style={{marginTop: '0pt', marginLeft: '36pt', marginBottom: '0pt', textIndent: '72pt', widows: 0, orphans: 0, fontSize: '10.5pt'}}><span>&nbsp;</span></p>
      <p style={{marginTop: '0pt', marginBottom: '0pt', textIndent: '72pt', widows: 0, orphans: 0, fontSize: '10.5pt'}}><span>(e)</span><span style={{width: '27.57pt', textIndent: '0pt', display: 'inline-block'}}>&nbsp;</span><u><span>Injunctive Relief and Irreparable Harm</span></u><span>. Recipient agrees that Recipient’s breach of the obligations of this Section may cause the Disclosing Party irreparable damage for which recovery of money damages may be inadequate. The Disclosing Party will, therefore, be entitled to seek timely injunctive relief to protect its rights under these T&amp;Cs without the necessity of proving damages, in addition to any and all remedies available at law or equity.</span></p>
      <p style={{marginTop: '0pt', marginLeft: '36pt', marginBottom: '0pt', textIndent: '72pt', widows: 0, orphans: 0, fontSize: '10.5pt'}}><span>&nbsp;</span></p>
      <p style={{marginTop: '0pt', marginBottom: '0pt', textIndent: '72pt', widows: 0, orphans: 0, fontSize: '10.5pt'}}><span>(f)</span><span style={{width: '28.37pt', textIndent: '0pt', display: 'inline-block'}}>&nbsp;</span><u><span>Return of Confidential Information</span></u><span>. Upon request of the Disclosing Party, Recipient shall: (i) return to the Disclosing Party all tangible forms of the Confidential Information; and (ii) destroy all electronic forms of the Confidential Information and all notes, reports or other documents prepared by Recipient that contains any Confidential Information, and in each case of (i) and (ii), in Recipient’s possession, custody or control, within 30 days of such request;&nbsp;</span><em><span>provided</span></em><span>&nbsp;</span><em><span>however</span></em><span>, that Recipient may retain a single copy of the Confidential Information for the sole purpose of determining the scope of Recipient’s obligations under these T&amp;Cs and any Order and</span><span>&nbsp;&nbsp;</span><span>as required for its own record keeping and audit purposes in the ordinary course of its business. Further, Recipient shall not be required to alter, modify, delete or destroy back-up media made in the ordinary course of business and stored in a manner designed to prevent unauthorized access or use of the Confidential Information. The returning of Confidential Information shall not relieve Recipient from compliance with other terms and conditions of these T&amp;Cs.&nbsp;</span></p>
      <p style={{marginTop: '0pt', marginLeft: '36pt', marginBottom: '0pt', textIndent: '72pt', widows: 0, orphans: 0, fontSize: '10.5pt'}}><span>&nbsp;</span></p>
      <p style={{marginTop: '0pt', marginBottom: '0pt', textIndent: '72pt', widows: 0, orphans: 0, fontSize: '10.5pt'}}><span>(g)</span><span style={{width: '26.86pt', textIndent: '0pt', display: 'inline-block'}}>&nbsp;</span><u><span>Survival</span></u><span>. The confidentiality and non-use obligations set forth in this&nbsp;</span><u><span>Section&nbsp;</span></u><span>shall survive and continue in force for a period of 10 years following the date of disclosure of the Confidential Information. Notwithstanding the foregoing, trade secrets shall be treated as Confidential Information for as long as they retain their status as trade.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '0pt', textIndent: '72pt', widows: 0, orphans: 0, fontSize: '10.5pt'}}><span>&nbsp;</span></p>
      <p style={{marginTop: '0pt', marginBottom: '13.8pt', fontSize: '10.5pt'}}><strong><span style={{color: '#3d3d3d'}}>Electronic Communications and Notices</span></strong></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>When you visit the Website, send or respond to requests via the Website or e-mail Scientist.com and/or PhenoVista, you are communicating electronically. You consent to receive communications from Scientist.com and PhenoVista electronically. Scientist.com’s default method of Electronic Communication is email, however we may respond to you by sending messages through the Services if that is how you initially contacted us. You agree that all agreements, notices, disclosures and other communications that Sciemtist.com provides to you electronically relating to these TofU satisfy any legal requirement that such communications be in writing.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>Notices sent to Scientist.com must be sent to&nbsp;</span><a href="mailto:legal@scientist.com" style={{textDecoration: 'none'}}><span style={{color: '#0072bc'}}>legal@scientist.com</span></a><span style={{color: '#3d3d3d'}}>. Notices sent by email are deemed delivered the first Business Day after the date of sending as long as the sender does not receive notice of bounce back or non delivery within two Business Days of sending.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '13.8pt', fontSize: '10.5pt'}}><strong><span style={{color: '#3d3d3d'}}>Account Information and Password</span></strong></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>In order to access the Services, you will have to create an account using your current valid e-mail address. You may only create one account per email address. You acknowledge, consent, and agree that Scientist.com may access, preserve and disclose your account information and User Content if required to do so by law or in a good faith belief that such access preservation or disclosure is reasonably necessary to (a) comply with legal process; (b) enforce these TofU; (c) respond to any claim that User Content violates any laws or regulations or the rights of third parties; (d) provide certain customized features of the Services to you, if any; (e) respond if you contact Scientist.com for any reason; or (f) protect the rights, property, or personal safety of Scientist.com, its other Users, and the public. When you register for the Services you will be asked to provide a password. As you will be responsible for all activities that occur under your password, you should keep your password confidential. You are solely responsible for maintaining the confidentiality of your account and password, and you agree to accept responsibility for all activities that occur under your account or password. If you have reason to believe that your account is no longer secure (for example, in the event of a loss, theft, or unauthorized disclosure or use of your account ID or password), you shall immediately notify Scientist.com. YOU ARE SOLELY LIABLE FOR LOSSES INCURRED BY YOU, SCIENTIST.COM OR OTHERS DUE TO ANY UNAUTHORIZED USE OF YOUR ACCOUNT.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '13.8pt', fontSize: '10.5pt'}}><strong><span style={{color: '#3d3d3d'}}>Services Availability</span></strong></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>Scientist.com may make changes to or discontinue any of the products or services available within the Services at any time, and without notice.&nbsp;</span></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><strong><span style={{color: '#3d3d3d'}}>License and Website Access&nbsp;</span></strong></p>
      <p style={{marginTop: '14pt', marginBottom: '14pt', fontSize: '10.5pt'}}><span>Scientist.com grants to Client a limited non-exclusive, non-transferrable right and license, solely for its legitimate and lawful business purposes to: (a) use the Services; and (b) permit its Users to access and use the Website for the purposes set forth in these TofU and the Terms and Conditions for Purchases, specifically to send requests for goods and services provided by Phenovista and enter into Orders for the same.&nbsp;</span></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>This license does not include any resale or commercial use of the Services, including without limitation, the Website or its contents; any collection and use of any service listings, descriptions, or prices; any derivative use of the Website or its contents; any downloading or copying of account information for the benefit of another third party or merchant; or any use of data mining, robots, or similar data gathering and extraction tools. The Services (including without limitation the Website) or any portion of them may not be reproduced, duplicated, copied, sold, resold, visited, reverse engineered or otherwise exploited for any commercial purpose without express written consent of Scientist.com. You may not frame or utilize framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of the Services (including without limitation, the Website) without express written consent. You may not use any meta tags or any other "hidden text" utilizing Scientist.com's name or trademarks without the express written consent of Scientist.com. Any unauthorized use terminates the permission or license granted by Scientist.com. You are granted a limited, revocable, and nonexclusive right to create a hyperlink to the home page of the Website so long as the link does not portray Scientist.com, or its products or services in a false, misleading, derogatory, or otherwise offensive matter. You may not use any Website logo or other proprietary graphic or trademark as part of the link without express written permission.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '13.8pt', fontSize: '10.5pt'}}><strong><span style={{color: '#3d3d3d'}}>Indemnification</span></strong></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>THE CLIENT AGREES TO INDEMNIFY AND HOLD HARMLESS SCIENTIST.COM, AND ITS PARENT, SUBSIDIARIES, AFFILIATES OR ANY RELATED COMPANIES (INCLUDING THOSE WHICH SHARE SUBSTANTIALLY COMMON OWNERSHIP), AND THE OFFICERS, DIRECTORS, EMPLOYEES, AGENTS AND REPRESENTATIVES OF ANY OF THEM FROM ANY AND ALL CLAIMS, LOSSES, OBLIGATIONS, DAMAGES, LIABILITIES, COSTS, DEBT, AND EXPENSES (INCLUDING ATTORNEY’S FEES) ARISING OUT OF (I) YOUR AND/OR YOUR USERS’ USE OR MISUSE OF THE SERVICES; (II) YOUR AND/OR YOUR</span><span style={{color: '#3d3d3d'}}>&nbsp;&nbsp;</span><span style={{color: '#3d3d3d'}}>USERS’ USER CONTENT, INCLUDING SCIENTIST.COM’S STORAGE, POSSESSION, DISPLAY OR OTHER EXERCISE OF ITS LICENSE RIGHTS GRANTED HEREIN WITH RESPECT TO YOUR AND/OR YOUR USERS’ USER CONTENT; (III) VIOLATION OF THESE TERMS BY THE CLIENT OR ANY OF ITS USERS; (IV) VIOLATION BY YOU AND/OR YOUR USERS OF THE RIGHTS OF ANY OTHER PERSON OR ENTITY, INCLUDING, WITHOUT LIMITATION, CLAIMS THAT ANY USER CONTENT INFRINGES OR VIOLATES ANY THIRD PARTY INTELLECTUAL PROPERTY RIGHTS OR RIGHTS OF CONFIDENTIALITY OR IS IN BREACH OF ANY APPLICABLE LAWS OR REGULATIONS; (V) BREACH OF THE FOREGOING REPRESENTATIONS, WARRANTIES, AND COVENANTS BY YOU AND/OR YOUR USERS; AND (VI) ANY UNAUTHORIZED USE OF YOUR ACCOUNT NOT CAUSED BY SCIENTIST.COM. SCIENTIST.COM RESERVES THE RIGHT, AT YOUR EXPENSE, TO ASSUME THE EXCLUSIVE DEFENSE AND CONTROL OF ANY MATTER FOR WHICH YOU ARE REQUIRED TO INDEMNIFY US AND YOU AGREE TO COOPERATE WITH OUR DEFENSE OF THESE CLAIMS. YOU AGREE NOT TO SETTLE ANY MATTER GIVING RISE TO YOUR INDEMNIFICATION OBLIGATIONS WITHOUT THE PRIOR WRITTEN CONSENT OF SCIENTIST.COM. SCIENTIST.COM WILL USE REASONABLE EFFORTS TO NOTIFY YOU OF ANY SUCH CLAIM, ACTION, OR PROCEEDING UPON BECOMING AWARE OF IT.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '13.8pt', fontSize: '10.5pt'}}><strong><span style={{color: '#3d3d3d'}}>Disclaimer of Warranties and Limitation of Liability</span></strong></p>
      <p style={{marginTop: '14pt', marginBottom: '14pt', fontSize: '10.5pt'}}><span style={{textTransform: 'uppercase'}}>THE SERVICES AND ALL INFORMATION, CONTENT (including without limitation, User content and third party content), MATERIALS, PRODUCTS (INCLUDING SOFTWARE) AND FEATURES INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH THE SERVICES ARE PROVIDED BY SCIENTIST.COM ON AN "AS IS" AND "AS AVAILABLE" BASIS, UNLESS OTHERWISE SPECIFIED IN WRITING. SCIENTIST.COM MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THE SERVICES OR THE INFORMATION, CONTENT, MATERIALS, PRODUCTS (INCLUDING SOFTWARE) OR FEATURES INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH THE SERVICES, OR THE GOODS AND SERVICES ADVERTISED AND/OR OFFERED FOR SALE BY Phenovista VIA THE WEBSITE, UNLESS OTHERWISE SPECIFIED IN WRITING. YOU EXPRESSLY AGREE THAT YOUR USE OF THE SERVICES IS AT YOUR SOLE RISK.&nbsp;</span></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span>TO THE FULL EXTENT PERMISSIBLE BY APPLICABLE LAW, SCIENTIST.COM DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. SCIENTIST.COM DOES NOT WARRANT THAT THE SERVICES, INFORMATION, CONTENT, MATERIALS, PRODUCTS (INCLUDING SOFTWARE) OR FEATURES INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH THE SERVICES; THEIR SERVERS; OR E-MAIL SENT FROM SCIENTIST.COM ARE SECURE, FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.&nbsp;</span></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span>SCIENTIST.COM WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING FROM THE USE OF THE SERVICES OR FROM ANY INFORMATION, CONTENT, MATERIALS, PRODUCTS (INCLUDING SOFTWARE) OR FEATURES INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH THE SERVICES, INCLUDING, BUT NOT LIMITED TO DIRECT, INDIRECT, INCIDENTAL, PUNITIVE, AND CONSEQUENTIAL DAMAGES, UNLESS OTHERWISE SPECIFIED IN WRITING. WITHOUT PREJUDICE TO THE ABOVE, TO THE EXTENT PERMITTED BY APPLICABLE LAW, SCIENTIST.COM’S MAXIMUM LIABILITY TO YOU UNDER THESE TofU OR RELATING TO OR ARISING FROM THE SERVICES SHALL NOT EXCEED $100 (ONE HUNDRED US DOLLARS).</span></p>
      <p style={{marginTop: '0pt', marginBottom: '0pt', fontSize: '10.5pt'}}><span>SCIENTIST.COM IS NOT RESPONSIBLE FOR UNDERTAKINGS BETWEEN YOU AND PHENOVISTA, FOR CONTENT PROVIDED BY YOU, PHENOVISTA OR ANY OTHER THIRD PARTY, OR FOR ANY ACT OR OMISSION OF YOU OR THE PHENOVISTA AND ASSUMES NO LIABILITY THEREFOR AND HEREBY DISCLAIMS ANY AND ALL SUCH LIABILITY.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>CERTAIN STATE LAWS DO NOT ALLOW LIMITATIONS ON IMPLIED WARRANTIES OR THE EXCLUSION OR LIMITATION OF CERTAIN DAMAGES. IF THESE LAWS APPLY TO YOU, SOME OR ALL OF THE ABOVE DISCLAIMERS, EXCLUSIONS, OR LIMITATIONS MAY NOT APPLY TO YOU, AND YOU MIGHT HAVE ADDITIONAL RIGHTS.&nbsp;</span></p>
      <p style={{marginTop: '0pt', marginBottom: '13.8pt', fontSize: '10.5pt'}}><strong><span style={{color: '#3d3d3d'}}>Reservation of Rights</span></strong></p>
      <p style={{marginTop: '0pt', marginBottom: '0pt', fontSize: '10.5pt'}}><span>Scientist.com retains the right to immediately halt any sale of any goods or services on the Website; prevent or restrict access to the Services; take any other action to restrict access to or availability of any listing; or generally take any action not prohibited by applicable law.</span><span>&nbsp;&nbsp;</span><span>Scientist.com retains the right to edit in good faith Client reviews of goods and services purchased via the Website and to publicly display or share such reviews with third parties via</span><span>&nbsp;&nbsp;</span><span>Scientist.com’s own online marketplace and platform (the “Platform”). Scientist.com shall be entitled to use summary statistics generated through the use of the Services (including the Website) and other similar “meta” information generated through the use of the Services (including the Website), provided that in each case, any Client identifying information is removed from such data or information and no Client-specific information is disclosed.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '0pt', fontSize: '10.5pt'}}><span>&nbsp;</span></p>
      <p style={{marginTop: '0pt', marginBottom: '13.8pt', fontSize: '10.5pt'}}><strong><span style={{color: '#3d3d3d'}}>Applicable Law</span></strong></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>By using the Services, you agree that the laws of the State of Delaware, without regard to principles of conflict of laws, will govern these TofU and any dispute of any sort that might arise between you and Scientist.com.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '13.8pt', fontSize: '10.5pt'}}><strong><span style={{color: '#3d3d3d'}}>Disputes</span></strong></p>
      <p style={{marginTop: '0pt', marginBottom: '12pt', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>The Parties shall attempt to amicably resolve any dispute relating in any way to your use of the Services or these TofU. In the event any such dispute cannot be so resolved within 30 (thirty) days, such dispute shall be submitted to confidential arbitration in the State of Delaware, USA, except that, to the extent you have in any manner violated or threatened to violate Scientist.com’s intellectual property rights or rights of confidentiality, Scientist.com may seek injunctive or other appropriate relief in any state or federal court in the State of California, and you consent to exclusive jurisdiction and venue in such courts. Arbitration under this agreement shall be conducted under the rules then prevailing of the American Arbitration Association. The arbitrator's award shall be binding and may be entered as a judgment in any court of competent jurisdiction. To the fullest extent permitted by applicable law, no arbitration under this Agreement shall be joined to an arbitration involving any other party subject to this Agreement, whether through class arbitration proceedings or otherwise.</span></p>
      <p style={{marginTop: '0pt', marginBottom: '13.8pt', fontSize: '10.5pt'}}><strong><span style={{color: '#3d3d3d'}}>Our Address</span></strong></p>
      <p style={{marginTop: '0pt', marginBottom: '0pt', fontSize: '10.5pt'}}><span style={{color: '#3d3d3d'}}>Scientist.com</span></p>
      <p style={{marginTop: '0pt', marginBottom: '0pt', fontSize: '10.5pt'}}><span>329 S Highway 101,</span></p>
      <p style={{marginTop: '0pt', marginBottom: '0pt', fontSize: '10.5pt'}}><span>Suite 230,</span></p>
      <p style={{marginTop: '0pt', fontSize: '10.5pt'}}><span>Solana Beach, California, 92075, USA</span></p>
    </div>
  </div>
)
/* eslint-enable max-len, react/no-unescaped-entities */
