nextAuthUrl: "https://phenovista.softserv.cloud/api/auth"
providerName: "phenovista"
providerId: "12527"
scientistApiVersion: "v2"
nextPublicToken: $NEXT_PUBLIC_TOKEN
nextAuthSecret: $NEXTAUTH_SECRET
clientSecret: $CLIENT_SECRET
clientId: $CLIENT_ID
sentryAuthToken: $SENTRY_AUTH_TOKEN
sentryDsn: 'https://8e15464aee1fdfc31f70ed416c6bfdc9@o1008683.ingest.sentry.io/4506236741025792'
sentryOrg: 'scientist-inc'
sentryProject: 'phenovista'
sentryUrl: 'https://sentry.io/'
replicaCount: 1

image:
  repository: ghcr.io/scientist-softserv/webstore
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: "0.0.2"

imagePullSecrets:
  - name: github

ingress:
  enabled: true
  className: "nginx"
  annotations: {
    nginx.ingress.kubernetes.io/proxy-body-size: "0",
    cert-manager.io/cluster-issuer: letsencrypt-prod
  }
  hosts:
    - host: phenovista.softserv.cloud
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - phenovista.softserv.cloud
      secretName: softservcloud
