# we are running the deploy through vercel now so we don't need this github action
# TODO(alishaevn): fix any potential sentry error's if we switch from vercel to an in house deploy infrastructure

# name: "Deploy"
# run-name: Deploy (${{ github.ref_name }} -> ${{ inputs.environment }}) by @${{ github.actor }}
# on:
#   workflow_dispatch:
#     inputs:
#       environment:
#         description: 'Deploy to Environment'
#         required: true
#         default: 'staging'
#         type: choice
#         options:
#           - staging
#       debug_enabled:
#         type: boolean
#         description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
#         required: false
#         default: false

# jobs:
#   deploy:
#     uses: scientist-softserv/actions/.github/workflows/deploy.yaml@v0.0.10
#     secrets: inherit
