import { Title } from '@scientist-softserv/webstore-component-library'

const TermsAndConditions = () => (
  <div class='container'>
    <Title title='Terms and Conditions For Purchase' />
    {termsAndConditions}
  </div>
)

export default TermsAndConditions

const termsAndConditions = (
  <body>
    <p>Last Updated: October 19, 2023</p>
    <p>Welcome to the PhenoVista website (the “<span class='underline'>Website</span>”).</p>

    <p>By using the Website to place an Order with <b>PhenoVista Biosciences, Inc.</b>, with offices at 6195 Cornerstone Court E, #114, San Diego CA 92121 (“<span class='underline'>PhenoVista</span>,” “<span class='underline'>Supplier</span>,” “<span class='underline'>we</span>,” “<span class='underline'>us</span>” or “<span class='underline'>our</span>”) for products or services which are sold on the Website (“<span class='underline'>Services</span>”) you will be deemed to have read, understood, and agreed to these Terms and Conditions for Purchases (“<span class='underline'>T&amp;Cs</span>”). Please read these T&amp;Cs carefully and if you are unhappy with any aspect or do not have the authority to bind Client (as defined below) you represent in the order for Services made via the Website on its behalf (“<span class='underline'>Order</span>”), then you should not place the Order with us for that Client.</p>

    <p>We amend these T&amp;Cs from time to time. Please check the top of this page to see when these T&amp;Cs were last updated. The T&amp;Cs in force at the time the Quote (as defined below) is provided to the Client (as defined below) will apply to that respective Order.</p>

    <p>“<span class='underline'>Client</span>” or “<span class='underline'>you</span>” is either: (a) the individual placing an Order on their own behalf, or (b) the legal entity whose representative is using the Website to place the Order in the name of such legal entity on its behalf.</p>

    <p>These T&amp;Cs are between you and Supplier. The Assay Depot, Inc. (d/b/a Scientist.com), with offices at 505 Lomas Santa Fe Drive, Suite 110, Solana Beach, San Diego, CA 90275 (“<span class='underline'>Scientist.com</span>”) is also a party to these T&amp;Cs for its role in the ordering, billing and payment processes set forth herein. You, Supplier and Scientist.com are each a “<span class='underline'>Party</span>” and together the “<span class='underline'>Parties</span>.”</p>

    <p>Only parties that can lawfully enter into and form contracts under applicable law may place Orders via the Website. By placing an Order via the Website, Client hereby represents and warrants to Supplier and Scientist.com that Client has the ability to enter into and form contracts, including these T&amp;Cs and all Orders, and to the extent an Order is made on behalf of any entity or other organization, the individual making such Order is authorized to bind such entity or other organization to that Order (including these T&amp;Cs).</p>

    <p><b>1. SERVICES.</b></p>
    <ol type='a'>
      <li><span class='underline'>Services</span>. Supplier will provide Client with the Services, Records (defined below) and Deliverables (defined below) as agreed upon in each Order.</li>

      <li><span class='underline'>Orders</span></li>
      <ol type='i'>
        <li><i>RFPs, Quote and Purchase Orders</i>. For any Services that Client wishes to purchase, Client may use the Website to send a request to Supplier (“<span>Customer Request for Proposal</span>”). Supplier may respond to such request by providing a quote (“<span>Quote</span>”) which shall be valid for 30 days (“<span>Validity Period</span>”). The Quote will include a description of the Services, Deliverables (as defined below), Records (as defined below), the turn-around time, cost (including, as applicable, delivery, upfront payments, taxes, milestone payments and payment requirements) and any other relevant information. The Quote may refer to supplemental documents with information not contained in or directly attached to the Quote. The information contained in these supplemental documents is considered part of the corresponding Order. Client may place an Order in the Validity Period for the Services on the terms of the respective Quote by issuing a purchase order to Scientist.com via the Website (“<span>Purchase Order</span>”). Scientist.com shall then, as soon as reasonably possible and in any event within 2 Business Days, forward a corresponding Purchase Order to Supplier (“<span>Scientist Purchase Order</span>”). “<span>Business Days</span>” means Monday through Friday except for U.S. federal or state holidays.</li>
          <ol type='A'>
            <li>All Orders resulting from any Customer Request for Proposal made via the Website must be placed via the Website.</li>
            <li>Each Order shall start on the commencement date specified in the Order (“<span>Effective Date</span>”).</li>
          </ol>
        <li><i>Binding Effect</i>. Each Order shall come into effect and become binding on the Parties upon the issuance of the Scientist Purchase Order to Supplier. No physical signature is required to establish the Order. Each Order includes the Quote and is governed by the version of these T&amp;Cs in force at the time the Quote was provide to Client.</li>

        <li><i>Conflicts</i>. Any varying or additional general terms and conditions contained in any Quote, Purchase Order, Scientist Purchase Order, invoice or other notification or document in relation to the request or Order in question shall be of no effect, except as set forth in these T&amp;Cs. To be valid, any such varying or additional terms must be set forth in the Quote, referencing the specific section of these T&amp;Cs to be amended for the Order in question. Where any such amendment impacts any rights, obligations, or liabilities of Scientist.com, such amendment shall not be effective or binding unless and until agreed in writing by an authorized signatory of Scientist.com. For the avoidance of doubt, no changes to these T&amp;Cs can be included as part of an attachment within the Order.</li>
      </ol>
      <li><span class='underline'>Changes / Modifications to Orders</span>. Supplier shall not accumulate charges, and Client shall not be liable for payments, above the amounts specifically authorized by each Order, except as provided in this Section. Any amendments, alteration in the scope of Services or the fees pertaining to an Order must be placed via the Website, with a new Quote, Purchase Order and Scientist Purchase Order being issued for such change.</li>

      <li><span class='underline'>Correction of Material Errors</span>. In the event that Client provides Supplier with a written detailed notification of a material error by Supplier in any Services or Deliverables, at Client’s election, Supplier shall either: (i) correct the material error free of charge to Client as soon as reasonably possible; (ii) re-perform the Services as soon as reasonably possible and at Supplier’s sole cost and expense; or (iii) refund to Client the amount paid to Supplier for such Service or Deliverables.</li>

      <li><span class='underline'>Personnel</span>. Supplier will ensure: (i) all personnel who perform any Services under these T&amp;Cs are appropriately trained and qualified to perform the Services; and (ii) all personnel perform the Services in compliance with all applicable laws, rules and regulations.</li>

      <li><span class='underline'>Subcontracting</span>. Supplier shall not subcontract any of the Services unless approved in advance by Client in writing (email is sufficient), such approval not to be unreasonably withheld. In the event Client approves of any such subcontracting by Supplier, Supplier shall remain responsible for the performance of any such permitted subcontractor hereunder and for their compliance with the terms and conditions of these T&amp;Cs. Supplier shall be responsible for any and all payments to such permitted subcontractors.</li>

      <li><span class='underline'>Materials</span>.</li>
      <ol type='i'>
        <li>Client may transfer to Supplier certain Client proprietary or other materials to be used by Supplier and its employees and subcontractors solely for the limited and express purpose of providing the Services hereunder (such materials, together with any derivatives thereof made by Supplier, collectively the “<span>Materials</span>”). Neither Supplier nor its subcontractors will make any attempt to reverse-engineer, elucidate or ascertain the structure, composition, amino acid or genetic sequence of, or otherwise characterize, any of the Materials, except as otherwise expressly permitted by these T&amp;Cs.</li>

        <li>Supplier understands that the Materials are not to be sold, transferred or otherwise distributed by Supplier and/or its subcontractors to any third party or used for any purpose other than performance of the Services hereunder without the prior written consent of an authorized representative of Client. The Materials shall not be used in any research that is subject to consulting, licensing, assignment or similar obligations to any person or entity other than Client. The Materials will not be used in or for humans in any manner, including for the purpose of diagnostic testing.</li>

        <li>All Materials are provided “AS-IS,” are experimental in nature and should be used with appropriate caution, since not all their characteristics are known. SUPPLIER ACKNOWLEDGES THAT ALL CLIENT MATERIALS ARE SUPPLIED TO SUPPLIER WITHOUT ANY REPRESENTATION OR WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING ANY WARRANTY OF MERCHANTABILITY, TITLE, FITNESS FOR A PARTICULAR PURPOSE OR NONINFRINGEMENT OF PROPRIETARY RIGHTS, ALL OF WHICH ARE EXPRESSLY DISCLAIMED.</li>
      </ol>

      <li><span class='underline'>Performance</span>. Supplier will perform the Services in a professional, diligent, workmanlike, and timely manner, and in strict accordance with the terms and conditions of these T&amp;Cs and all Applicable Laws. “<span>Applicable Laws</span>” shall mean all federal, state and local laws, ordinances, regulations and codes applicable to Supplier and the Services, including but not limited to any applicable data privacy laws, export control laws and the Federal Food, Drug and Cosmetic Act and the regulations promulgated pursuant thereto, and if applicable, Good Laboratory Practices, Good Clinical Practices and Good Manufacturing Practices, as those terms are used by the U.S. Food and Drug Administration.</li>

      <li><span class='underline'>Records and Recordkeeping</span>. Supplier shall create and maintain written quality records of the results, data, reports and/or or Deliverables (defined below) generated or recorded in the performance of the Services (collectively, the “<span>Records</span>”) in a timely and accurate manner. The Records shall be and hereby are owned by Client. Supplier shall maintain the Records in compliance with the terms and conditions of these T&amp;Cs and all Applicable Laws. Promptly upon completion or termination of Services, or promptly upon request by Client, Supplier shall transfer the Records to Client.</li>
    </ol>

    <p><b>2. PAYMENT AND EXPENSES.</b></p>
    <ol type='a'>
      <li><span class='underline'>Payment</span>. Payment for Services shall be in accordance with the terms set forth in each Order and these T&amp;Cs, or a pro rata amount thereof in the event of an early termination pursuant to <span>Section 4</span> below. However, in no event shall the total fee thereunder exceed the total fee amount set forth in each Order. Invoices are payable in accordance with <span>Section 2(d)</span> below.</li>

      <li><span class='underline'>Reimbursable Expenses</span>. Client will only reimburse Supplier for reasonable out-of-pocket expenses actually incurred by Supplier in rendering Services under these T&amp;Cs, provided that such expenses: (i) are approved in advance in the Order or in writing by Client; and (ii) are submitted within 30 days of incurring such expense.</li>

      <li><span class='underline'>Travel Expenses</span>. If applicable in connection with the Services, Client shall reimburse reasonable travel expenses actually incurred by Supplier, without commission or mark-up: (i) if approved in advance in an Order or in writing by Client, and only to the extent that such costs are in accordance with Client’s then-current corporate travel policy; and (ii) if submitted within 30 days of incurring such expense. Client shall make its then-current corporate travel policy available upon request by Supplier.</li>

      <li><span class='underline'>Invoices</span>. All invoices relating to an Order shall be issued to Client by Scientist.com. Client shall pay such invoices within 30 days of receipt (in the currency set forth in the Order) to the Scientist.com bank account detailed on the invoice. If an Order requires a down payment prior to performance of Services, then Client will pay Scientist.com the down payment as set forth in the Order and Scientist.com will initiate a wire transfer to Supplier’s bank account within 10 days of clearing Client’s down payment. The compensation payable by Client is exclusive of value added tax, sales taxes or similar taxes, which, if payable, shall be borne and paid by Client.</li>

      <li><span class='underline'>Refunds</span>. If Supplier owes any refunds for any particular Order, then Supplier shall pay such refunds to Scientist.com, who shall in turn pay an equal sum to Client within 10 Business Days of receipt thereof, and Supplier and Scientist.com shall credit any applicable invoices accordingly. For clarity, Scientist.com’s obligation to make such payment to Client is expressly conditioned upon Scientist.com receiving such monies from Supplier.</li>
    </ol>

    <p><b>3. TERM.</b> The Order shall commence as of the Effective Date and shall continue in force until completion of the Services, or until terminated as provided in <span>Section 4</span>, whichever occurs first (the “<span>Term</span>”). The Order may be extended for additional periods only upon the mutual written consent of Supplier and Client.</p>

    <p><b>4. TERMINATION.</b></p>
    <ol type='a'>
      <li><span>No Termination by Scientist.com</span>. Once an Order is entered into, only Supplier and Client (and not Scientist.com) may terminate such Order in accordance with these T&amp;Cs.</li>
      <li><span>Termination Without Cause</span>. Supplier or Client may terminate an Order without cause upon 30 days’ prior written notice to each other and to Scientist.com. Client may terminate an Order immediately upon notice to Supplier in the event of a breach of any representation or covenant in <span>Sections 5(d)</span> or <span>5(e)</span>.</li>
      <li><span>Termination For Cause</span>. Supplier or Client may terminate an Order if the other materially breaches these T&amp;Cs or the Order; <i>provided</i> <i>that</i>: (i) the non-breaching Party shall have provided breaching Party with at least 30 days’ prior written notice of such material breach and the opportunity to cure the breach during such period; and (ii) the non-breaching Party notifies Scientist.com in writing of any such termination.</li>
      <li><span>Effect of Termination</span>. Upon notice of any termination of an Order, Supplier shall promptly wind-down and cease performance of the applicable Services, and Supplier shall use commercially reasonable efforts to minimize the cost attributable to such wind-down efforts. Client’s sole obligation upon termination shall be to pay Scientist.com for Services performed up to the date of termination. If Client has an obligation to make any payments resulting from termination of an Order, the relevant invoice shall be transmitted by Supplier to Scientist.com no later than 60 days after the effective date of termination, and Scientist.com shall forward a corresponding invoice to Client no later than 10 Business Days thereafter.</li>
      <ol type='i'>
        <li>Supplier shall deliver promptly to Client a copy of all undelivered Deliverables and Records;</li>
        <li>at Client’s election, Supplier shall deliver to Client or destroy all Materials in accordance with Applicable Laws;</li>
        <li>Supplier shall return any pre-payment funds provided by Client that are unearned as of expiration or termination of these T&amp;Cs;</li>
        <li>each Party shall return or destroy all the other Party’s Confidential Information in accordance with <span class='underline'>Section 6(g)</span>; and</li>
        <li><span class='underline'>Section 13(i)</span> will apply.</li>
      </ol>
    </ol>

    <p><b>5. OBLIGATIONS AND REPRESENTATIONS.</b></p>
    <ol type='a'>
      <li><span class='underline'>By Supplier</span>. Supplier hereby represents that: (i) Supplier will apply the degree of skill, care and diligent supervision necessary to ensure that the Services and Deliverables will be of high quality, proper and sufficient for the purpose contemplated, and in accordance with the standards of care and diligence regularly practiced by recognized professional firms performing work of a similar nature; (ii) Supplier’s performance of the Services shall comply with Applicable Laws; (iii) all work under these T&amp;Cs shall be Supplier’s original work and none of the Services or Deliverables infringe, misappropriate, or violate any proprietary rights of any third party; (iv) the terms of these T&amp;Cs are not inconsistent with Supplier’s other contractual arrangements; and (v) Supplier has the rights to assign to Client the Deliverables, Records and Intellectual Property (as defined below) pursuant to these T&amp;Cs.</li>

      <li><span class='underline'>Authority</span>. Each Party represents that: (i) it has the right, power and authority to enter into and perform these T&amp;Cs; (ii) it has obtained all necessary authorizations or waivers to enter into these T&amp;Cs and perform its obligations hereunder; and (iii) its execution, delivery and performance of these T&amp;Cs does not and will not conflict with or violate any agreement (whether express, implied or by operation of law) with any other party or any other legal obligation. Except as otherwise agreed upon in the Order, no other payments as a result of the Services provided hereunder (e.g., overhead charges or facility fees) are due to Supplier or any third party.</li>

      <li><span class='underline'>Non-Infringement</span>. Supplier represents that all Services and Deliverables furnished under these T&amp;Cs will not infringe upon or violate a U.S. patent, trademark or copyright held, or misappropriate a trade secret claimed, by a third party. If Client becomes subject to any such claim as indicated above, whether directly or indirectly, then Client shall notify Supplier of such claim and Supplier shall indemnify Client in accordance with <span>Section 8</span> below. If any part of the Services or Deliverables is held in any such suit to constitute infringement and its use is enjoined, Supplier shall, at its sole expense, at any time after the claim of infringement arises, promptly either: (i) secure for Client the perpetual right to continue the use of such part of the Services or Deliverables by procuring for Client a royalty-free license or such other permission as will enable Supplier to secure suspension of any injunction; or (ii) replace that part of the Services or Deliverables with an adequate non-infringing part to modify it so that it becomes non-infringing, but only if the replacement or modification is acceptable to Client. For clarity, the remedies in this Section shall not apply to the extend the alleged infringement is due to Client’s Confidential Information, Materials or other data, documents or materials provide by Client to Supplier to perform the Services.</li>

      <li><span class='underline'>Debarment</span>. Supplier represents that neither it nor of any of its employees providing Services hereunder has been debarred under the provisions of the Generic Drug Enforcement Act of 1992, as amended (21 U.S.C. Sec. 335a(a) and (b)). If Supplier or any of its employees providing Services becomes debarred or receives notice of or threat of debarment during the Term, Supplier shall immediately notify Client in writing and cease all work hereunder. Debarment may result in immediate termination of these T&amp;Cs.</li>

      <li><span class='underline'>Exclusion</span>. Supplier represents that neither it nor any of its employees providing Services hereunder has been excluded from any federal health care program including, but not limited to, Medicare, Medicaid and the Civilian Health and Medical Program of the Uniformed Services. If Supplier or any of its employees providing Services hereunder is excluded during the Term, Supplier shall immediately notify Client in writing and cease all work hereunder. Exclusion may result in immediate termination of these T&amp;Cs.</li>

      <li><span class='underline'>Warranty Disclaimer</span>. EXCEPT FOR THE WARRANTIES EXPRESSLY SET FORTH IN THESE T&amp;Cs, NO PARTY MAKES ANY WARRANTIES, AND EACH PARTY HEREBY DISCLAIMS ALL OTHER WARRANTIES, ORAL OR WRITTEN, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, RELATING TO THESE T&amp;Cs OR ANY ORDER, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR ANY PARTICULAR PURPOSE, AND ALL WARRANTIES ARISING FROM COURSE OF PERFORMANCE, COURSE OF DEALING OR USAGE IN TRADE. FURTHER, SUPPLIER MAKES NO WARRANTIES WITH REGARD TO THE RESULTS OBTAINED FROM THE OPERATION OR USE OF ANY DELIVERABLE PROVIDED HEREUNDER. CLIENT ACKNOWLEDGES THAT ALL SERVICES PERFORMED BY SUPPLIER ARE OF A RESEARCH NATURE AND THEREFORE PERFORMANCE AND OUTCOMES CANNOT BE GUARANTEED.</li>
    </ol>

    <p><b>6. CONFIDENTIALITY AND SCIENTIST.COM’S RIGHTS.</b></p>
    <ol type='a'>
      <li><span class='underline'>Not Applicable between Scientist.com and Client</span>. This <span>Section 6</span> applies between: (i) Supplier and Client; and (ii) Scientist.com and Supplier. It does not apply as between Scientist.com and Client. Obligations of confidentiality between Scientist.com and Client are set forth in the Scientist.com Website Terms of Use (the “<span>Terms of Use</span>”). This <span>Section 6</span> and references to “Party,” “Parties,” “Recipient” and “Disclosing Party” contained in this <span>Section 6</span> shall be construed accordingly.</li>

      <li><span class='underline'>Confidential Information</span>. “<span>Confidential Information</span>” means any and all confidential, proprietary and/or trade secret information or materials that are disclosed by or on behalf of a Party or its affiliates (the “<span>Disclosing Party</span>”) to the other Party or its affiliates (the “<span>Recipient</span>”) under these T&amp;Cs, whether in written, oral or other form. Confidential Information includes, without limitation, business plans, business practices, business records, compounds, concepts, current and past distribution and production arrangements, customer information, data, Deliverables, designs, devices, employee information, financial information, formulas, intellectual property, inventions, know-how, marketing and sales strategies, materials, methods, plans, procedures, processes, <span>products and future products,</span> <span>protocols</span>, <span>research and development data and plans</span>, Records, software, specifications, technical information and trade secrets.</li>

      <li><span class='underline'>Non-Disclosure and Non-Use</span>. Subject to <span>Sections 6(d) and 6(e)</span>, Recipient shall maintain the Confidential Information in confidence, and not disclose the Confidential Information to any third party, or use the Confidential Information for its benefit or the benefit of any third party, without the prior written consent of the Disclosing Party. Recipient shall use the Confidential Information only as is necessary to perform the Services and/or fulfill its obligations pursuant to these T&amp;Cs and any Order, and shall limit any disclosure to its directors, officers, employees, contractors, agents and permitted subcontractors (“<span>Representatives</span>”) on a “need-to-know” basis for purposes of performing the Services and/or fulfilling its obligations under these T&amp;Cs and any Order. Recipient shall cause its Representatives to comply with the confidentiality obligations set forth in this <span>Section 6</span> and shall be liable for any violation of the confidentiality obligations set forth in this <span>Section 6</span> by any of its Representatives. Recipient shall protect the Disclosing Party’s Confidential Information with at least the same degree of care that Recipient uses to protect its own Confidential Information, but in no case less than reasonable care.</li>

      <li><span class='underline'>Exceptions</span>. Confidential Information shall not include any information that Recipient can demonstrate as evidenced by competent written evidence: (i) previously was in its possession, as shown by its pre-existing records, without violation of any obligation of confidentiality; (ii) has become publicly known through no wrongful act of Recipient; (iii) was received by Recipient without breach of these T&amp;Cs from a third party without restriction as to the use and disclosure of the information; or (iv) was independently developed by Recipient without use of the Confidential Information.</li>

      <li><span class='underline'>Authorized Disclosures</span>. Confidential Information may be disclosed by Recipient if Recipient is required by a valid order of a court or other governmental body or otherwise required by the law to disclose such Confidential Information; <i>provided</i>, <i>however</i>, that, if legally permissible, Recipient shall give the Disclosing Party timely written notice of such a requirement before doing so and shall cooperate with the Disclosing Party to seek a protective order, confidential treatment or other appropriate measures. Scientist.com shall also have the right to use and disclose the Confidential Information as authorized and/or required to perform its obligations under these T&amp;Cs and/or the Terms of Use, and in the event of any conflict between such Terms of Use and any provision in these T&amp;Cs, the Terms of Use shall prevail. PhenoVista and the Client are not the Representatives of Scientist.com.</li>

      <li><span class='underline'>Injunctive Relief and Irreparable Harm</span>. Recipient agrees that Recipient’s breach of the obligations of this <span>Section 6</span> may cause the Disclosing Party irreparable damage for which recovery of money damages may be inadequate. The Disclosing Party will, therefore, be entitled to seek timely injunctive relief to protect its rights under these T&amp;Cs without the necessity of proving damages, in addition to any and all remedies available at law or equity.</li>

      <li><span class='underline'>Return of Confidential Information</span>. Upon request of the Disclosing Party, Recipient shall: (i) return to the Disclosing Party all tangible forms of the Confidential Information; and (ii) destroy all electronic forms of the Confidential Information and all notes, reports or other documents prepared by Recipient that contains any Confidential Information, and in each case of (i) and (ii), in Recipient’s possession, custody or control, within 30 days of such request; <i>provided</i> <i>however</i>, that Recipient may retain a single copy of the Confidential Information for the sole purpose of determining the scope of Recipient’s obligations under these T&amp;Cs and any Order. Scientist.com may also retain a copy of the Confidential Information as required for its own record keeping and audit purposes in the ordinary course of its business. Further, Recipient shall not be required to alter, modify, delete or destroy back-up media made in the ordinary course of business and stored in a manner designed to prevent unauthorized access or use of the Confidential Information. The returning of Confidential Information shall not relieve Recipient from compliance with other terms and conditions of these T&amp;Cs.</li>

      <li><span class='underline'>Survival</span>. The confidentiality and non-use obligations set forth in this <span>Section 6</span> shall survive expiration or any termination of the Order and will continue in force for a period of 10 years following the effective date of such expiration or termination of the Order. Notwithstanding the foregoing, trade secrets shall be treated as Confidential Information for as long as they retain their status as trade.</li>
    </ol>

    <p><b>7. OWNERSHIP OF RESULTS AND INTELLECTUAL PROPERTY.</b></p>
    <ol type='a'>
      <li>“<spa class='underline'n>Intellectual Property</spa>” shall mean any and all concepts, data, developments, discoveries, documentation, electronic code, formulae, ideas, improvements, innovations, inventions, know-how, methodologies, modifications, processes, processes, rights, techniques, trade secrets and writings (whether or not protectable under state, federal or foreign patent, trademark, copyright or similar laws) or the like, whether or not written or otherwise fixed in any form or medium, regardless of the media on which contained and whether or not patentable or copyrightable, and all intellectual property rights therein.</li>

      <li><span class='underline'>Deliverables</span>. Except as set forth in <span>Sections 7(c)</span>, all Deliverables and Records provided by Supplier to Client pursuant hereto, whether or not patentable, copyrightable, or susceptible to any other form of legal protection which are made, conceived, reduced to practice, or authored by Supplier or Supplier personnel as a result of the performance of Services, or to the extent derived from use or possession of Client’s Materials or Confidential Information (collectively, the “<span>Deliverables</span>”) shall be the sole and exclusive property of Client upon full payment of all sums due from Client for each such Deliverable and/or Record under these T&amp;Cs. Subject to <span>Sections 7(c)</span>, each Deliverable and/or Record constituting an original work shall be considered a work made for hire under applicable copyright laws. Subject to <span>Sections 7(c)</span>, Supplier hereby assigns, and agrees to assign, to Client all right, title, and interest in all worldwide Intellectual Property rights in the Deliverables and Records upon full payment of all sums due from Client under the Order for each such Deliverable and/or Record under these T&amp;Cs.</li>

      <li><span class='underline'>Supplier Intellectual Property</span>. Notwithstanding anything to the contrary set forth herein, to the extent any Deliverable, Record or work made for hire includes Supplier’ concepts, ideas, models, know-how, software, source or object code, method of manufacture, methodologies, technology, techniques, procedures, management tools, workshops, manuals, data files, inventions, and other Intellectual Property that Supplier has developed, created, or acquired independent of performing the Services or independent of any Client’s Materials or Confidential Information (“<span>Supplier IP</span>”), Supplier shall retain exclusive ownership in such Supplier IP. Any improvements, alterations, or enhancements to Supplier IP shall be the sole property of Supplier. Upon full payment of all sums due by Client under the Order for each Deliverable and/or Record, Supplier hereby grants Client a royalty-free, fully paid-up, perpetual, irrevocable, sublicensable, worldwide, non-exclusive right and license to use any Supplier IP in connection with Client’s use of the Deliverable and/or Record. For the avoidance of doubt, Client and Supplier agree that any source or object code previously owned or licensed by Supplier or created hereunder are not a part of the rights provided to Client and may be used by Supplier on behalf of itself or any of its other clients.</li>

      <li><span class='underline'>Furnished Property</span>. All documents, records, apparatus, equipment and other physical property furnished to Supplier on behalf of Client or developed by or on behalf of Client pursuant to an Order shall remain and be the sole property of Client and returned promptly upon Client’s request. Notwithstanding the foregoing, Supplier agrees to return and deliver all such property upon expiration or termination of such Order.</li>

      <li><span class='underline'>No Other Rights</span>. Except as set forth in these T&amp;Cs and the Terms of Use, no Party shall acquire any license or other Intellectual Property interest, by implication or otherwise, under or to any Intellectual Property owned or controlled by the other Party.</li>
    </ol>

    <p><b>8. INDEMNIFICATION AND LIMITATION OF LIABILITY.</b></p>
    <ol type='a'>
      <li><span class='underline'>By Supplier</span>. Supplier shall indemnify and hold Client, its affiliates, and their respective officers, directors, agents and employees (collectively, “<span>Client Indemnitees</span>”) harmless from and defend against any and all liabilities, losses, damages or expenses of any kind, including costs and reasonable attorneys’ fees (collectively “<span>Losses</span>”) arising out of or resulting from any third party suits, proceedings, actions, claims or demands (collectively, “<span>Claims</span>”) to the extent resulting from: (i) performance of Services; (ii) any grossly negligent or willful acts or omissions by a Supplier Indemnitee; or (iii) Supplier’s breach of these T&amp;Cs or any Order. Notwithstanding the foregoing, Supplier will not be obligated to indemnify any Client Indemnitee to the extent that the applicable Claim is within the scope of Client’s indemnification obligations under <span>Section 8(b)</span> below.</li>

      <li><span class='underline'>By Client</span>. Client shall indemnify and hold Supplier, its affiliates, and their respective officers, directors, agents, and employees (collectively, “<span>Supplier Indemnitees</span>”) harmless from and defend against any and all Losses arising out of or resulting from Claims to the extent resulting from: (i) any grossly negligent or willful acts or omissions by Client Indemnitee; (ii) Client’s breach of these T&amp;Cs or any Order; (iii) Client’s failure to comply with any applicable laws, ordinances, regulations and codes; or (iv) any product liability claim relating to Client’s products. Notwithstanding the foregoing, Client will not be obligated to indemnify any Supplier Indemnitee to the extent that the applicable Claim is within the scope of Supplier’s indemnification obligations under <span>Section 8(a)</span> above.</li>

      <li><span class='underline'>Indemnification of Scientist.com</span>. Client and Supplier will each indemnify and hold Scientist.com, its affiliates, and their respective officers, directors, agents, and employees (collectively, “<span>Scientist Indemnitees</span>”) harmless from and their defend against any and all Losses arising out of or resulting from Claims to the extent resulting from any breach of their respective obligations under these T&amp;Cs and/or any Order.</li>

      <li><span class='underline'>Indemnification Conditions and Procedures</span>. Each Party’s agreement to indemnify, defend and hold the other Party harmless pursuant to this <span>Section 8</span> is conditioned upon the indemnified Party: (i) providing prompt written notice to the other Party of any relevant Claim; (ii) assisting and fully cooperating with the indemnifying Party, at the indemnifying Party’s reasonable expense, in the investigation of, preparation for and defense of any such Claim; (iii) permitting the indemnifying Party to assume full responsibility and authority to investigate, prepare for, defend against and settle any such Claim; and (iv) not compromising or settling any such Claim without the indemnifying Party’s written consent; <i>provided, however</i>, that the indemnified Party will be entitled to participate in the defense of such Claim and to employ at its own expense counsel to assist therein. Neither Party will be responsible or bound by any settlement of any Claim admitting fault or incurring any liability made without its prior written consent; <i>provided</i>, <i>however</i>, that the indemnified Party will not unreasonably withhold or delay such consent.</li>

      <li><span class='underline'>Limitation of Liability AND SCIENTIST.COM DISCLAIMER</span>. No Party shall be responsible or liable with respect to any subject matter of these T&amp;Cs or ANY order, for any special, indirect, incidental, consequential, exemplary or punitive damages (including for lost profits) or for any matter beyond its reasonable control, whether in contract, warranty, negligence, tort, strict liability or otherwise, arising out of, based on, or relating to these T&amp;Cs, any quote and/or ANY order (even if foreseeable or in the contemplation of such Party). EXCEPT FOR client’s and supplier’s breaches of CONFIDENTIALITY obligations under <span>section 6</span> and client’s and supplier’s INDEMNIFICATION OBLIGATIONS under <span>Section 8</span>, THE TOTAL LIABILITY OF client and supplier UNDER THESE T&amp;Cs SHALL NOT EXCEED THE TOTAL AMOUNT OF fees paid (or payable) under THESE T&amp;Cs during the previous 12 months preceding to the claim. SCIENTIST.COM’S MAXIMUM LIABILITY TO CLIENT AND SUPPLIER RESULTING OR ARISING FROM ANY BREACH OF SCIENTIST.COM’S OBLIGATIONS IN THESE T&amp;CS SHALL NOT EXCEED ONE HUNDRED U.S. DOLLARS ($100 USD) PER ORDER. SCIENTIST.COM IS NOT RESPONSIBLE FOR (AND HEREBY DISCLAIMS ANY AND ALL LIABILITY EXPRESS OR IMPLIED FOR): (i) UNDERTAKINGS BETWEEN CLIENT AND SUPPLIER; (ii) THE SERVICES, DELIVERABLES AND/OR RECORDS; (iii) ANY ACTS OR OMISSIONS OF ANY OTHER PARTY INCLUDING, WITHOUT LIITATION, BREACH OF THESE T&amp;CS, ANY ORDER AND/OR TERMS OF USE; AND/OR (iv) ANY WRONGDOING OR NEGLIGENCE OF ANOTHER PARTY.</li>
    </ol>

    <p><b>9. AUDIT, REVIEW OF WORK AND INSPECTIONS.</b></p>
    <ol type='a'>
      <li><span class='underline'>Audit</span>. During the Term, or such longer period as may be required by Applicable Laws, Client shall have access to books and records maintained by Supplier in connection with these T&amp;Cs as reasonably necessary for Client to: (i) audit or inspect Supplier’s performance and compliance with these T&amp;Cs; and (ii) to verify the accuracy of amounts invoiced and paid hereunder. Client, or its designated agent, shall have the right to inspect such records for up to 2 business days during regular business hours at Supplier’s offices upon giving Supplier written notice of at least 30 days before the intended date of such audit or inspection. Client shall be responsible for all expenses it incurs in connection with any audit or inspection.</li>

      <li><span class='underline'>Review of Work</span>. During the Term, Supplier will permit Client’s Representative(s) to examine the work performed hereunder and to inspect Supplier’s and its permitted subcontractors’ facilities during regular business hours, and upon reasonable advanced written notice.</li>

      <li><span class='underline'>Inspections</span>. If any governmental or regulatory authority conducts or gives notice to Supplier of its intent to conduct an inspection at Supplier’s facilities or take any other regulatory action, Supplier will promptly give Client written notice thereof, including all information pertinent thereto.</li>
    </ol>

    <p><b>10. INSURANCE.</b> Supplier and Client will have and maintain such types and amounts of liability insurance as is normal and customary in the industry generally for parties similarly situated, and as adequate to satisfy each Party’s respective obligations under these T&amp;Cs. Upon written request, Supplier and/or Client will provide to the requesting Party a copy of its policies of insurance in that regard, along with any endorsements, schedules, or riders thereto.</p>

    <p><b>11. DISPUTE RESOLUTION.</b> In the event that any dispute arises relating to these T&amp;Cs or any Order, the Parties shall promptly meet and attempt to resolve same through good faith discussions. Scientist.com may, at its discretion, be involved in discussions regarding disputes relating to or arising from the Services and/or payment. If the Parties are unable to resolve any dispute to their mutual satisfaction within 30 days after they commence discussions regarding same, then each Party will be free to pursue any available remedy at law or in equity in accordance with <span>Section 13(d)</span>. Each Party will bear its own legal fees and any costs incurred under this Section. During a dispute, no interest shall accrue on relevant invoices issued by Supplier to Scientist.com or Scientist.com to Client.</p>

    <p><b>12. NOTICES.</b> All notices, requests and demands, other than routine communications under these T&amp;Cs, will be in writing and will be deemed to have been duly given when delivered by an overnight courier with a reliable system for tracking delivery, or by email with email confirmation of receipt by the recipient. Notices to each Party shall be sent to the person named at the signature line for such Party and addressed as first set forth above. A copy of notices sent to Client shall also be sent via email to James G. Evans, CEO, PhenoVista Biosciences, Inc., at james@phenovista.com. Notices sent to Scientist.com shall be sent to Scientist.com by email to legal@scientist.com. Either Party may from time to time change the individual(s) to receive notices under this Section and/or its address for notification purposes by giving the other Party prior written notice of the new individual(s) and/or address and the effective date of the change.</p>

    <p><b>13. MISCELLANEOUS.</b></p>
    <ol type='a'>
      <li><span class=''>Assignment</span>. No Party may assign any Order or any of its rights, duties or obligations hereunder without the other Parties’ prior written consent; except that no Party may assign an Order, without the other Parties’ prior written consent, to: (i) an affiliate; or (ii) an entity that acquires all or substantially all of the business or assets of the assigning Party relating to the subject matter of the Order, whether by merger, acquisition or otherwise. No assignment will relieve any Party of the performance of any accrued obligation that such Party may then have under these T&amp;Cs or any Order. Any assignment not in accordance with this Section shall be null and void.</li>

      <li><span class=''>Remedies</span>. The rights and remedies provided to each Party in these T&amp;Cs are cumulative and in addition to any other rights and remedies available to such Party at law or in equity.</li>

      <li><span class=''>Entire Agreement; Amendment</span>. These T&amp;Cs and the Order constitute the entire agreement between Client, Scientist.com and Supplier with respect to Order and Services set forth therein and supersedes all previous negotiations, commitments and writings with regard thereto.</li>

      <li><span class=''>Arbitration of Disputes; Waiver of Jury Trial</span>. Any dispute or claim arising out of or relating to these T&amp;Cs and any Order, whether in contract, tort or otherwise, shall be settled and decided by final and binding arbitration before the Judicial Arbitration and Mediation Service (“<span>JAMS</span>”). The arbitration will be conducted by one arbitrator in Wilmington, Delaware, and administered by and in accordance with the then existing streamlined Rules of Practice and Procedure of JAMS. In rendering the award in the arbitration, the arbitrator shall determine the rights and obligations of the Parties according to the substantive and procedural laws of Delaware. The prevailing Party in any arbitration hereunder shall be awarded reasonable attorneys’ fees, expert and non-expert witness costs and expenses, and all other costs and expenses incurred in connection with the arbitration. The Parties acknowledge that by agreeing to arbitration, they are giving up the right to a jury trial. The arbitrator shall have the power to award any and all types of relief, legal or equitable, including, without limitation, injunctive or declaratory relief. The award rendered by the arbitrator shall be final, and judgment on any arbitration award may be entered by any court of competent jurisdiction.</li>

      <li><span class=''>Force Majeure</span>. No liability shall result from delay in performance or non-performance by any Party caused by act of God, fire, flood, war, pandemic, epidemic, government action or other circumstances beyond the reasonable control of the non-performing Party (including internet failure beyond the reasonable control of the non-performing Party) (collectively “<span>Events of Force Majeure</span>”). Any Party claiming benefit of this clause shall, without delay, notify the other Party in writing of the occurrence and on the cessation of an Event of Force Majeure. The non-performing Party shall use all reasonable efforts to eliminate, cure or overcome an Event of Force Majeure and resume performance of its obligations with all possible speed.</li>

      <li><span class=''>Independent Contractors</span>. Save as otherwise agreed in writing between the relevant Parties, the Parties are independent contractors. Representatives of the Parties are not and will not be deemed employees of any other party. Supplier shall be responsible for all earnings reports and all withholding, employment, and payroll tax payments to all federal, state and local governmental authorities, including without limitation the IRS and the Social Security Administration. Supplier shall not receive any of the retirement and welfare benefits provided to Client’s employees and Supplier shall not be covered under Client’s Worker’s Compensation Insurance policy. Supplier shall have no authority to enter into any contract or agreement on behalf of Client or to otherwise bind Client without Client’s prior written consent.</li>

      <li><span class=''>No Waiver</span>. No waiver of any term or condition of these T&amp;Cs will be construed as a waiver of any other term or condition. No failure to exercise any right or demand performance of any obligation under these T&amp;Cs will be deemed a waiver of such right or obligation.</li>

      <li><span class=''>Severability</span>. The provisions of these T&amp;Cs are severable, and any judicial determination that any provision(s) is invalid or unenforceable will not affect the validity or enforceability of any other provision, but rather will cause these T&amp;Cs first to be construed in all respects as if such invalid or unenforceable provision(s) were modified to terms that are valid and enforceable but, if necessary, will cause these T&amp;Cs to be construed as if such invalid or unenforceable provision(s) were omitted.</li>

      <li><span class=''>Continuing Obligations</span>. The provisions set forth in these T&amp;Cs that by their terms have continuing obligations, or that which logically, by their nature, are intended to survive, will survive termination or expiration of these T&amp;Cs. Such provisions include, but are not limited to, payment, obligations and representations, confidentiality, intellectual property, indemnification, termination, dispute resolution, choice of law and jurisdiction. Final payment by Client will not constitute a waiver by Client of possible claims for continuing obligations on the part of Supplier.</li>

      <li><span class=''>Headings</span>. The headings in these T&amp;Cs are provided for convenience only and do not affect the meaning of these T&amp;Cs.</li>
    </ol>
  </body>
)
